### ISSUE TITLE
对右键菜单内容筛减后，打开右键菜单时会闪现一下

### ISSUE THREAD

**Issue by Sunsh4j** [xh321/LiteLoaderQQNT-Custom-CSS#1]
如下图：
![动画](https://github.com/xh321/LiteLoaderQQNT-Custom-CSS/assets/43169575/15fc373f-ed14-49bb-a7f2-64ed7bc69280)
----------------------------------------------------------------------------------------------------------------------
隐藏菜单选项是用的
css选择器{
     display: none !important;
}

这个有办法优化一下吗？

**Comment by xh321** [comment]
按理说不应该有这个问题的，可能是QQ固有的问题。这个CSS插件只会写入CSS到头部，然后没有任何别的操作了。任何效果都是CSS自行生效的结果。

**Comment by Sunsh4j** [comment]
> 按理说不应该有这个问题的，可能是 QQ 固有的问题。这个 CSS 插件只会写入 CSS 到头部，然后没有任何别的操作了。任何效果都是 CSS 自行生效的结果。

忽然发现qq启动后，一开始会显示原来的样式，过了2s后，才能显示css设置的样式

**Comment by xh321** [comment]
如果没有别的问题的话暂时先关闭issue了，这个问题我估计是qq自己的问题

**Comment by Sunsh4j** [comment]
> 如果没有别的问题的话暂时先关闭issue了，这个问题我估计是qq自己的问题

嗯嗯， 好的
